### ISSUE TITLE
bad toke in $-line?

### ISSUE THREAD

**Issue by JacobLauinger** [oracc/editing#10]
We have a number of cases where obverse and reverse cannot be distinguished, so we are using @face a and @face b to designate the surfaces.  Then we are using, e.g., $ beginning of face a broken to indicate when the beginning of that face is no longer extant.  Trying to follow the documentation here:

http://oracc.museum.upenn.edu/doc/help/editinginatf/quickreference/index.html

Both the checker in Nammu and the oracc check command are giving us warnings though, and we are not sure what is wrong.  Thanks in advance for any guidance.
<img width="434" alt="screen shot 2019-01-29 at 12 48 31 pm" src="https://user-images.githubusercontent.com/29659861/51929058-5306e100-23c5-11e9-91fd-b6db8f159580.png">

**Comment by EleanorRobson** [comment]
Put the content of these $-lines in parentheses:

$ (face a broken)
