### ISSUE TITLE
project down

### ISSUE THREAD

**Issue by JacobLauinger** [oracc/editing#7]
Hello - Just checking to see if projects are down for maintenance, or if there is something wrong with mine in particular?  The glossaries are completely gone, and the texts show the atf files not the html versions.  I do not see any errors when I check the project, and I've tried rebuilding the project a few times.  The problem started yesterday at about 3pm EST.

**Comment by stinney** [comment]
There is a new issue with attributes that I am working on now; I'll update as soon as it's fixed.

**Comment by stinney** [comment]
Update: I tested the new version of the ATF processor with some fixes for the attributes issue on aemw/amarna and it looked good, so I've installed that and rebuilt the project which now looks to be back to normal.

**Comment by JacobLauinger** [comment]
Yes, everything is normal for me as well, thanks!!!
